version: '2'
services:
  web:
    build: .
    environment:
      WEBSITE_TITLE: 'Zaperon Client Download'
      WEBSITE_HOME_CONTENT: 'Zaperon Client Download'
      WEBSITE_NAV_LOGO: ''
      WEBSITE_APP_TITLE: 'Zaperon Client Download'
      APP_USERNAME: admin
      APP_PASSWORD: HIRE123
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_NAME: releaseserver
      DB_PASSWORD: HIRE123
      # DEKs should be 32 bytes long, and cryptographically random.
      # You can generate such a key by running the following:
      #   require('crypto').randomBytes(32).toString('base64')
      # PLEASE ENSURE THAT YOU CHANGE THIS VALUE IN PRODUCTION
      DATA_ENCRYPTION_KEY: oIh0YgyxQbShuMjw4/laYcZnGKzvC3UniWFsqL0t4Zs=
      # Recommended: 63 random alpha-numeric characters
      # Generate using: https://www.grc.com/passwords.htm
      TOKEN_SECRET: Z77vwHSIHd76863UuYXVrqHlefxewqWzkwtrObGB4wpZTVv61MHzgn8erpA2LkB
      APP_URL: 'https://uat-download.zaperon.com'
      ASSETS_PATH: '/usr/src/electron-release-server/releases'
    depends_on:
      - db
    ports:
      - '8081:80'
    entrypoint: ./scripts/wait.sh db:5432 -- npm start
    volumes:
      - ./releases:/usr/src/electron-release-server/releases
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: HIRE123
      POSTGRES_USER: postgres
      POSTGRES_DB: releaseserver
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
